edition = "2021"
max_width = 100
use_small_heuristics = "Max"

tab_spaces = 4
hard_tabs = false
newline_style = "Unix"

fn_call_width = 90
chain_width = 60
struct_lit_width = 20
match_arm_leading_pipes = "Preserve"

reorder_imports = true
reorder_modules = true
merge_derives = true
